name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run build command
        run: npm run predeploy # Replace 'build' with your actual npm build script

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../dist # Replace 'dist' with the actual folder containing your build output
          publish_branch: gh-pages # Specify the target branch (e.g., gh-pages)
          force_orphan: true # Optional: Create an orphan branch if it doesn't exist
